- README.md
Modify Readme file with explanation.
> Some change in readme file to more clearance

- css/settings.css
Center settings page buttons #14
> Setting page, align center

- templates/Settings.html
Fix update button in settings page. User need to confirm if update is needed.
see issue #21
> Search for update

- css/dark_theme.css
- custom.js
- js/functions.js
- js/themesettings.js
- theme.json
- themesettings.html
Added dark_theme.css @EdddieN put your css code for dark theme here.
Add new function turn on and off switch instead of bigtext.
> Rewrite and add new functions

- css/dashboard_show_last_update.css
- custom.js
- js/functions.js
- theme.json
- themesettings.html
And some other fixes.
Added popup if Settings.html not exists in templates folder.
> Function Show Last Seen on Dashboard

- custom.css
When a device is timed out. It fades out.
default theme:
machinon theme:
> Device timeout

- custom.css
> Added Open Sans font

- custom.css
Add blue border to protected switch, and red for low battery,
> Added borders lowbattery, Protected

- custom.css
Changed protected to green and add more red to timedout items
> Added blue border on hover

- custom.css
- custom.js
- js/functions.js
- js/standby.js
- js/themesettings.js
- theme.json
- themesettings.html
Added new theme feature. Standby screen (screensaver). Change amount of minutes in theme settings.
Added "Save Settings".
> Added Standby Screen (screensaver)

- custom.css
> Low Battery

- custom.css
> Fix transparent windows

- js/functions.js
- theme.json
- themesettings.html
Also gray out function that not can be set..
> Options to disable switch on Scene Devices

- custom.js
Fixes issue no #121 and no #89
> Dropdown close after click tab. Removes line in footer

- custom.js
Reverts EdddieN/machinon-domoticz_theme#124
On desktop the theme settings menu disappears.
On mobile all the menu dissapears
> Revert "Dropdown close after click tab. Removes line in footer"

- custom.css
Make a change to fix flex bug. But i need more time to review other things.
> Fix flex bug

- custom.css
- js/functions.js
This fixes the log button on temperature page for domoticz beta V4.10032 and above.
@EdddieN test if this works on erlier versions..
Issue #119
> Log button fix

- js/functions.js
with link to devices page #135
> Idx in options menu

- custom.js
- js/functions.js
With this you get a notification if security status changes..
> Notify secstatus

- custom.css
think Fix:
https://github.com/EdddieN/machinon-domoticz_theme/issues/154 
and this:
https://github.com/EdddieN/machinon-domoticz_theme/issues/111#issuecomment-429774183
> Landaisbenj patch 1

- js/check_update.js
- js/functions.js
- js/notify.js
- js/themesettings.js
Works like this:
1. Goto options
2. Click on notifications
3 Add your notifications, make sure browser is checked
4 Now you custom notification is viewed in the bar and in the notification log
> Notification Rewrite

- custom.css
Change tables background color
#168
> Table background color

- custom.css
Reverts EdddieN/machinon-domoticz_theme#171
> Revert "Update custom.css"

- js/check_update.js
- js/functions.js
- js/themesettings.js
#170  no notification logs on devices on/off, open/close. Just a visual notification fades in/out.
> Rewrite 2 Notifications

- css/dark_theme.css
- custom.css
> Landaisbenj table patch 1

- custom.css
> Update to grid

- templates/Settings.html
Missing translation Security Panel in settings menu
> Missing translation

- js/functions.js
- theme.json
- themesettings.html
Fade tile when device is off. (Only on/off devices).
enable/disable in theme settings menu.
> Fade when device is off

- custom.js
- js/functions.js
Similar to previous instances of absolute paths that work fine with typical Domoticz installs, but cause problems when Domoticz is behind a proxy server that rewrites the path from eg "192.168.1.100:8080/#/Dashboard" to be "192.168.1.100/domoticz/#/Dashboard"
> * Changed "/json.htm" absolute URLs to relative to work with proxy path rewrites

- custom.css
> Charts design close to zeplin mockups

- custom.js
Fix evenseditor margins when using sidemenu
> Visuel fixes

- custom.css
- custom.js
- js/functions.js
- js/settings_page.js
- Fix for the search function in all cases/screens
- Disable search input on setup screens
- Improve search usability on mobile
- Better design on desktop / mobile
- Support Escape key to reset field and search
- Support Return key to hide/unfocus search field (avoid a tap on mobile)
> Improve search feature

- css/dark_theme.css
- custom.css
- js/functions.js
- Bunch of fixes
- CSS clean-up (still need more work)
- Options popup automatically close when mouse leaves it
- Options symbol is now 3 vertical dots to gain space
- Display only dashboard sections with data
> Fixed and cleanup

- css/dashboard_columns.css
- custom.css
- js/functions.js
- theme.json
- themesettings.html
- On mobile, use native selector for better usability
- Support dashboard in columns for screen > 1200px (inspired from Aurora theme)
> New features

- css/dark_theme.css
- custom.css
On mobile, better display of settings
CSS Cleanup
> Better display of settings on mobile and CSS Cleanup

- css/floorplan.css
- custom.css
- custom.js
- js/themesettings.js
- New function: Saves settings to 2 uservariables
- Small fix in floorplan.css
- Add bootbox css code  to custom.css
> Save theme settings to Uservariable

- .gitattributes
- css/dashboard_camera.css
- css/dashboard_columns.css
- custom.css
- js/functions.js
> Ignore images/unorganised folder for the release files + Compact Dashboard

- custom.css
- theme.json
> Visual fixes buttons

- js/themesettings.js
> Fix unable to create uservariable

- css/icons_on_tabs.css
- custom.css
- custom.js
- js/themesettings.js
- theme.json
- themesettings.html
Example with a pattern:
If cover is chosed, the background is fixed.
> New feature: custom background (cover/pattern)

- css/dark_theme.css
> Fix JS error if camera list is empty

- custom.js
- js/dashboard_camera.js
- js/functions.js
- js/livestamp.js
- theme.json
- New feature: timeago is now refreshed and accurate
- Bug fixes:
- Cameras didn't work
- Temperature/weather widgets lost options/layout after being updated
> New release 1.14

- css/dark_theme.css
- custom.css
- custom.js
- js/check_update.js
- js/devices.js
- js/functions.js
- js/themesettings.js
- theme.json
> New release 1.15
